<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>NU1903</NoWarn>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kosa.ECommerce.Application\Kosa.ECommerce.Application.csproj" />
    <ProjectReference Include="..\Kosa.ECommerce.Infrastructure\Kosa.ECommerce.Infrastructure.csproj" />
    <ProjectReference Include="..\Kosa.ECommerce.Persistence\Kosa.ECommerce.Persistence.csproj" />
    <ProjectReference Include="..\Kosa.ECommerce.Shared\Kosa.ECommerce.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
